### ISSUE TITLE
bug: macOS Sonoma 4.1.2 Intel cannot download models

### ISSUE THREAD

**Issue by vlbosch** [janhq/jan#1556] opened 2024-01-12 10:38 UTC
**Describe the bug**
When trying to download any given model on the models page from Jan, the download starts but hangs at 0% and after a certain period of time just stops. No error is given.

**Steps to reproduce**
1. Go to Hub
2. Click on any "Download" button from any given model
3. Watch the download-bar come up and disappear again.
4. No error is presented, the progress-bar just disappears.

**Expected behavior**
Expect the download to start, or present an error with what the issue might be, that it doesn't start.

**Screenshots**

**Environment details**
- Operating System: MacOS Sonoma 14.2.1
- Jan Version: 0.4.3 stable
- Processor: Intel 12-Core Xeon W 3.3Ghz
- RAM: 96GB
- Any additional relevant hardware specifics: AMD Radeon Pro W5700X 16GB, 1TB SSD.

**Additional context**
Also tried downloading with Jan having full disk-access in the macOS settings (which I think it shouldn't need), but that didn't change described the behaviour.

**Comment by vlbosch** [comment] 2024-01-12 11:39
I just downloaded the Apple Silicon version of Jan 0.4.3 Stable on my M1 Max MacBook Pro. The issue is not present there; it runs on macOS Sonoma 14.0. Furthermore it runs out of the box as expected on AS, so without full disk access I can download and run any given model. Hence, the issue seems to manifest on the Intel version for macOS.

**Comment by cracksauce** [comment] 2024-01-13 19:42
@vlbosch Are you getting GPU acceleration with the AMD eGPU? If so, how? I'm also running Mac Intel build.

I have 64gb RAM and Jan is only running CPU inference with token speeds ~0.5/s on hub-downloaded Mistral 7b. Really desperate to speed things up.

**Comment by 0xSage** [comment] 2024-01-14 14:52
@vlbosch can you reproduce this on the nightly build? https://jan.ai/install/nightly/

**Comment by Van-QA** [comment] 2024-01-14 15:48
This issue is not happening on my Mac M2, and since our OfficeLab is lacking Mac Intel, I'm assigning this to @namchuai who is using Mac Intel to help reproduce this.

**Comment by namchuai** [comment] 2024-01-14 16:13
@vlbosch thank you for reporting the problem. Unfortunately, I'm not facing that issue. I can download normally.
![2024-01-14 23 08 11](https://github.com/janhq/jan/assets/10397206/18db767b-ebda-45c4-862e-d56bd7cc23c9)
![2024-01-14 23 08 14](https://github.com/janhq/jan/assets/10397206/0dee2fcc-a750-431a-bbce-0dd5b9c21fb3)
![2024-01-14 23 08 17](https://github.com/janhq/jan/assets/10397206/6e386a6e-2f7e-480e-98d2-a0a8d24256a2)

@vlbosch could you please try with the nightly build which @0xSage specified above? And if you still got that error, please help us to:
1. Ensure that you have privilege to write to ~/jan/models
2. Upload the log file at `/Users/$(whoami)/jan/logs` 

Thank you!

**Comment by vlbosch** [comment] 2024-01-15 12:50
> @vlbosch can you reproduce this on the nightly build? https://jan.ai/install/nightly/

I tried it with the nightly. The issue persists, but now I am presented with the error "TIMEDOUT" with something that seems like an IPv6-address. 

@namchuai I tried it with both full disk-access and without, but that doesn't make a difference. I will retrieve the log for you and upload it here.

**Comment by vlbosch** [comment] 2024-01-15 12:51
> @vlbosch Are you getting GPU acceleration with the AMD eGPU? If so, how? I'm also running Mac Intel build.
> 
> I have 64gb RAM and Jan is only running CPU inference with token speeds ~0.5/s on hub-downloaded Mistral 7b. Really desperate to speed things up.

I don't have an eGPU, on the Mac Pro it is directly via PCIe. Unfortunately Jan doesn't seem to accelerate with GPU support in Intel Macs. If it should and I just need to configure something, please let me know so I can try.

**Comment by vlbosch** [comment] 2024-01-15 19:45
[app.log](https://github.com/janhq/jan/files/13942533/app.log)

**Comment by namchuai** [comment] 2024-01-23 02:42
sorry for the delay. I don't see anything suspicious in log. I think we will need to do some work:
1. From Jan's side: incoporate more log in the next release to troubleshoot the issue.
2. Help from @vlbosch : could you re-validate below:

- You have permission to write to `~/Users/$(whoami)/jan`
- You have enough space on `/Users/$(whoami)` by checking Disk Utility
- Your internet are ready, you are not behind a proxy

Thank you for your help!

**Comment by 0xSage** [comment] 2024-02-14 08:35
Closing this given we are a few release past this. Please open up a new issue if this happens in any later releases, and pls include logs (which are hopefully more verbose now :) )

**Closed by 0xSage** 2024-02-14 08:35 UTC
Labels: status: can't reproduce, status: needs info, type: bug
