### ISSUE TITLE
bug: Model keeps reloading until out of memory followed by crash on macOS due to context length too large

### ISSUE THREAD

**Issue by vlbosch** [janhq/jan#2071] opened 2024-02-18 12:26 UTC
**Describe the bug**
Jan cannot load Qwen 1.5, more specifically 72b chat Q6. Going through the logs it appears to load correctly, then multiple Nitro errors are shown and the model will load again. Despite reloading, the previously reserved GPU memory is not released, so it reloads until all memory is reserved and the machine becomes unresponsive and ultimately crashed. 

**Steps to reproduce**
1. Download qwen1_5-72b-chat-q6_k.gguf
2. Create folder in models
3. Run Jan
4. Close Jan
5. Modify model JSON to also use gpu with setting ngl = 100
6. Start Jan
7. Run Qwen 1.5 72b chat Q6
8. View the memory pressure rising, dropping a bit and rising again
9. Mac becomes unresponsive and ultimately system crashes

**Expected behavior**
Model loads correctly or otherwise an error will be presented to the user, stating that the model is not supported/not recognized and cannot be loaded. 

Also, when failed to load a model, it is expected that the reserved GPU memory will be released, so the system will not become unresponsive due to multiple attempts to run the model.

**Environment details**
- Operating System: macOS Sonoma 14.3
- Jan Version: 0.4.6-273 nightly
- Processor: M3 Max 16C-40
- RAM: 128GB Unified RAM
- Any additional relevant hardware specifics: 40c GPU

**Logs**
See log.
[App-crashQwen.log](https://github.com/janhq/jan/files/14322472/App-crashQwen.log)

**Additional context**
Tried to load the model with various settings, also without GPU and ultimately the crash occurs after completely filling the memory. I now the model can run, because Ollama runs it like expected and I also run other ±70b parameter models in Q6.

**Comment by vlbosch** [comment] 2024-02-18 13:25
Just tried it with the latest nightly 274 and the issue is still present.

**Comment by vlbosch** [comment] 2024-02-18 13:39
Update: I retried with a smaller context size. 8192 instead of the context size of the model (32768). Now the model loads correctly and I can interact with it. The issues thus appears to be in the locking of memory for both the model and the full context length it might possibly use. 

Maybe this can be avoided by dynamically using context length on the fly? And maybe putting a limit on the context length (despite the model accepting more context) calculated based on maximum available memory?

**Comment by hahuyhoang411** [comment] 2024-02-19 03:02
We have a memory calculation formula here:

https://github.com/janhq/jan/issues/1432

cc @louis-jan

**Comment by tikikun** [comment] 2024-02-19 03:53
hi @0xSage @louis-jan this issue can easily be mitigated by constrained the context len to be below the chosen context len to be able to send.

On the llama cpp level @louis-jan has pointed out there is a pending issue upstream but that won't stop us from fixing this on Jan level

**Comment by louis-jan** [comment] 2024-03-07 02:40
Example for the calculation
https://rahulschand.github.io/gpu_poor

> We have a memory calculation formula here:
> 
> #1432
> 
> cc @louis-jan

**Comment by 0xSage** [comment] 2024-06-11 02:20
Dupe of #2320

**Closed by 0xSage** 2024-06-11 02:20 UTC
Labels: type: bug
