### ISSUE TITLE
Custom font for code text and answers 

### ISSUE THREAD

**Issue by MRCSIBR** [janhq/jan#3094] opened 2024-06-23 21:56 UTC
### #

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Please add a easy way to change fonts... font customization is missing in the settings icon.

### Some inspiration

Datalab has a very nice combination of Studio Feixen-Sans for their AI notebooks... please add to JAN

### Ideas

Using the 'settings' icon users should be able to change to desired font
`Iosevka SS15` for the code window could be a nice choice

### What is the motivation / use case for changing the behavior?

Font customization is missing

**Comment by MRCSIBR** [comment] 2024-06-24 02:43
Here is some sample code if anyone is interested: https://github.com/MRCSIBR/LLM-chat-simulation-with-Whatsapp-like-UI/blob/main/main.html

**Comment by 0xSage** [comment] 2024-09-05 09:29
Closing as dupe of #2846

**Closed by 0xSage** 2024-09-05 09:29 UTC
Labels: type: feature request
