### ISSUE TITLE
feat: Inference engine for Intel iGPU and intel GPU

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#915] opened 2023-12-08 08:57 UTC
**Problem**
- On machines with only Intel CPU (with/ without Intel Arc GPU), the main CPU have to work hard for the inference, it needs to offload as much as possible to the Intel Integrated GPU or external Intel Arc GPU

**Success Criteria**
- [x] Support for Intel iGPU and eGPU (Arc GPU) with Vulkan for coverage and possible speedup - #2056 
- [ ] Support for Intel iGPU and eGPU with `llama.cpp` sycl - https://github.com/ggerganov/llama.cpp/blob/master/README-sycl.md

**Comment by 0xSage** [comment] 2024-06-11 01:38
Closing. Sorta dupe of openvino issue in cortex repo

**Closed by 0xSage** 2024-06-11 01:38 UTC
Labels: P2: nice to have, type: feature request, engineering: Jan Inference Layer, platform: Windows
