### ISSUE TITLE
bug: cannot use OpenAI GPT3.5 Turbo

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1574] opened 2024-01-14 14:25 UTC
**Describe the bug**
I cannot use OpenAI GPT3.5 Turbo. Whenever i send a message, it responds `This model's maximum context length is 4097 tokens. However, you requested 4317 tokens (221 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.`

https://github.com/janhq/jan/assets/89722390/1f425b0e-8323-4747-8e43-26e64bb91f91

**Steps to reproduce**
1. Choose model GPT3.5 Turbo
2. Send message
3. See error

**Environment details**
- Operating System: MacOS Sonoma 14.2
- Jan Version: Jan v0.4.3-143
- Processor: Apple M2
- RAM: 6GB

**Logs**
JAN API listening at: http://127.0.0.1:1337

**Comment by 0xSage** [comment] 2024-01-14 14:37
@imtuyethan I was able to use 3.5 turbo on mine. Let's tag @Van-QA for UX/UI bugs like these so we get 1 additional person to reproduce these issues?

@Van-QA if you can repro, pls open this issue again.

**Comment by Van-QA** [comment] 2024-01-14 14:37
The root cause of this might be related to this: https://github.com/janhq/jan/issues/1559, will retest it again once this issue is resolved

**Comment by 0xSage** [comment] 2024-01-14 14:38
Ah yes, I was able to repro on a clean thread. Weird. @Van-QA we can close this one though since it's a dupe

**Closed by 0xSage** 2024-01-14 14:38 UTC
Labels: type: bug
