### ISSUE TITLE
bug: Actual settings pages are missing on "My Model" settings page

### ISSUE THREAD

**Issue by alexander-litvinovich** [janhq/jan#3308] opened 2024-08-08 11:56 UTC
### #

- [X] I have searched the existing issues

### Current behavior

The content of the settings pages is missing/invisible

### Minimum reproduction step

1. Go to Settings
2. Go to My models
3. Click on ⚙️ button close to Groq or Openui list

### Expected behavior

I expected to see at least something there 

### Screenshots / Logs

https://github.com/user-attachments/assets/a2131266-c34d-4367-813e-7c185438829d

### Jan version

0.5.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Environment details

Apple M2, MacOS Ventura 13.2.1 (22D68)

**Comment by Van-QA** [comment] 2024-08-21 07:30
@alexander-litvinovich, sorry for the inconvenience, the issue is resolved in our nightly build, would you mind trying it out? https://github.com/janhq/jan?tab=readme-ov-file#download
Feel free to reopen this if the issue persist

**Closed by Van-QA** 2024-08-21 07:30 UTC
Labels: type: bug

**Comment by alexander-litvinovich** [comment] 2024-08-21 08:46
Thanks! Just installing nightly build didn't help, but wiping jan data folder helped.
