### ISSUE TITLE
feat: Custom OpenAI compatible server support with preserved inference parameters

### ISSUE THREAD

**Issue by qnixsynapse** [janhq/jan#2840] opened 2024-04-29 04:09 UTC
**Problem**
Sometimes, people like me run an openai compatible server instead of running the model through Jan's nitro for better tailored to hardware compatibility and availability. The openai inference partially works when set like this:
![image](https://github.com/janhq/jan/assets/17230826/7b6a66c8-9f50-478b-836e-cfba9e85495c)

However, Inference parameters, such as  top_k, top_p, etc are not available. And some parameters such as temperature are not preserved. The model name is also incorrect as shown in the screenshot:
![Untitled](https://github.com/janhq/jan/assets/17230826/ea2ed6e9-abc0-46bb-9faf-17fd963a5429)

**Success Criteria**
It would be better to have support for a custom openai server. The list of models available can be queried through v1/models endpoint(if available).

**Comment by Van-QA** [comment] 2024-05-15 15:21
hi @qnixsynapse, 
You can achieve the same result by modifying the model.json value, take OpenAI GPT 4 turbo for example:
```
{
  "sources": [
    {
      "url": "https://openai.com"
    }
  ],
  "id": "gpt-4-turbo",
  "object": "model",
  "name": "OpenAI GPT 4 Turbo",
  "version": "1.2",
  "description": "OpenAI GPT 4 Turbo model is extremely good",
  "format": "api",
  "settings": {},
  "parameters": {
    "max_tokens": 4096,
    "temperature": 0.7,
    "top_p": 0.95,
    "stream": true,
    "stop": [],
    "frequency_penalty": 0,
    "presence_penalty": 0
  },
  "metadata": {
    "author": "OpenAI",
    "tags": [
      "General"
    ]
  },
  "engine": "openai"
}
```

The value from the settings will be visible in the UI I will be applied to the request
<img width="521" alt="image" src="https://github.com/janhq/jan/assets/64197333/6423b643-d855-4907-83c1-55b624ac829d">

Related article:
https://jan.ai/docs/remote-models/generic-openai

**Comment by qnixsynapse** [comment] 2024-05-23 12:53
@Van-QA Thank you! This helped. BTW, is it possible to provide a custom openai compatible endpoint for embeddings which is needed in "Knowledge retrieval"?

**Comment by Van-QA** [comment] 2024-05-23 15:23
> @Van-QA Thank you! This helped. BTW, is it possible to provide a custom openai compatible endpoint for embeddings which is needed in "Knowledge retrieval"?

hi @qnixsynapse you mean something like this? https://jan.ai/docs/remote-models/openai#how-to-integrate-openai-api-with-jan

**Comment by qnixsynapse** [comment] 2024-05-23 15:26
This is for large language model only. I use a smaller sentence transformer for the embeddings which is significantly faster than using embeddings from the main large model. So If I want to add an endpoint to the Jan app on some other port, will that be possible? Or sentence transformer support on the app using nitro is also a viable option.

**Comment by 0xSage** [comment] 2024-09-05 07:45
Closing as dupe of ^

**Closed by 0xSage** 2024-09-05 07:45 UTC
Labels: type: feature request
