### ISSUE TITLE
feat: Should be able to decide the model storage folder

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#317] opened 2023-10-10 08:34 UTC
**Problem**
Currently I don't know where the model is stored, i don't know how to clean up after i don't use it anymore 

**Success Criteria**
We can choose where to store the model folder

**Comment by 0xSage** [comment] 2023-10-12 05:08
dupe of #327 , keeping that issue as it has a bit more context

**Closed by 0xSage** 2023-10-12 05:08 UTC
Labels: type: feature request
