### ISSUE TITLE
bug: [0.5.9] - [1.0.3] Failed to fetch - cortex.cpp does not support special character in path

### ISSUE THREAD

**Issue by BrunnoFe** [janhq/jan#4048] opened 2024-11-19 14:43 UTC
### Jan version

0.5.8

### Describe the Bug

I keep getting this message when i try to download any model. Also, i am not able to use Jan default model for some reason.

![image](https://github.com/user-attachments/assets/c412fd44-09ed-48a1-9cf0-cfdcec582cdb)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by imtuyethan** [comment] 2024-11-20 06:05
@BrunnoFe Can you help send us app logs & cortex logs, here's how you can get them:
<img width="1071" alt="Screenshot 2024-11-20 at 1 04 33 PM" src="https://github.com/user-attachments/assets/78d56664-f62b-4752-9c75-3eb21b63d134">
Open `System monitor` > Click on `App Logs`

**Comment by BrunnoFe** [comment] 2024-11-22 15:54
Thanks for the answer! The logs are in the attached file.

[app.log](https://github.com/user-attachments/files/17872714/app.log)

I updated the application to the latest version (0.59) and now the error is different. The image below shows the error.

![image](https://github.com/user-attachments/assets/5c462a50-ff85-480b-9400-81e9807fac24)

Also, the log file is the most recent after the update.

**Comment by louis-jan** [comment] 2024-11-22 16:19
@BrunnoFe I think that’s because of the unsupported character in the username. Can you try with another user on your computer?

**Comment by imtuyethan** [comment] 2024-11-24 17:42
> @BrunnoFe I think that’s because of the unsupported character in the username. Can you try with another user on your computer?

Hmm can you elaborate more on this? :thinking:

**Comment by louis-jan** [comment] 2024-11-25 02:29
> > [@BrunnoFe](https://github.com/BrunnoFe) I think that’s because of the unsupported character in the username. Can you try with another user on your computer?
> 
> Hmm can you elaborate more on this? 🤔 What username is it?

See the program path, it indicates that the path is not valid. 

> Spawn cortex at path: C:\Users\Alguém\AppData\Roaming\Jan\data\extensions\@janhq\inference-cortex-extension\dist\bin\cortex-server.exe

Default data folder path: C:\Users\Algu�m\AppData\Roaming\Jan\data - utils/file_manager_utils.h:155

Both the cortex and llama.cpp files failed to function with those special characters.

**Comment by louis-jan** [comment] 2024-11-25 17:08
Reproducible 
1. Create a folder with the same username
2. Open Jan 
3. All folders are created accordingly from Jan
4. Could not spawn cortex-server.cpp

2024-11-25T17:06:42.691Z [APP]::Process exited with code 3221226505
2024-11-25T17:06:42.691Z [APP]::Restarting process in 5000ms (Attempt 5/5)
2024-11-25T17:06:47.694Z [APP]::Starting process: C:\Users\lephi\Desktop\Alguém\extensions\@janhq\inference-cortex-extension\dist\bin\cortex-server.exe --start-server --port 39291 --config_file_path C:\Users\lephi\Desktop\Alguém\.janrc --data_folder_path C:\Users\lephi\Desktop\Alguém
2024-11-25T17:06:47.709Z [APP]::Process error: Error opening file: No such file or directory

**Comment by louis-jan** [comment] 2024-11-25 17:10
Update: 

- Could not even open cortex-server.cpp from this folder. Moving to cortex.cpp. @vansangpfiev 

```json
logFolderPath: C:\Users\lephi\Desktop\Alguém
logLlamaCppPath: ./logs/cortex.log
logTensorrtLLMPath: ./logs/cortex.log
logOnnxPath: ./logs/cortex.log
dataFolderPath: C:\Users\lephi\Desktop\Alguém
maxLogLines: 100000
apiServerHost: 127.0.0.1
apiServerPort: 39291
checkedForUpdateAt: 0
checkedForLlamacppUpdateAt: 0
latestRelease: default_version
latestLlamacppRelease: ""
huggingFaceToken: ""
gitHubUserAgent: ""
gitHubToken: ""
llamacppVariant: windows-amd64-avx2-cuda-12-0
llamacppVersion: v0.1.39
enableCors: true
allowedOrigins:
  - http://localhost:39281
  - http://127.0.0.1:39281
  - http://0.0.0.0:39281
proxyUrl: ""
verifyProxySsl: true
verifyProxyHostSsl: true
proxyUsername: ""
proxyPassword: ""
noProxy: example.com,::1,localhost,127.0.0.1
verifyPeerSsl: false
verifyHostSsl: true
```

**Comment by louis-jan** [comment] 2024-11-26 02:29
Linked issue https://github.com/janhq/cortex.cpp/issues/1724

**Closed** 2024-12-02 02:56 UTC
Labels: P0: critical, type: bug, category: model support
