### ISSUE TITLE
feat: Multiple network profiles for models (API)

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3404] opened 2024-08-19 06:33 UTC
### #

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, the OpenAI model configuration only accepts one URL, but users like me often switch between multiple OpenAPI URLs depending on the use case. Manually editing the URL each time is time-consuming and inefficient.

### Describe the solution

A feature that allows users to create and manage multiple network profiles for different models.

### What is the motivation / use case for changing the behavior?

It'd be perfect for users who rely on multiple backends for different tasks.

**Comment by jens-totemic** [comment] 2024-08-31 16:25
Linking this up to my related issue: https://github.com/janhq/jan/issues/3404

**Comment by 0xSage** [comment] 2024-09-05 11:20
dupe of 3214, which explains better

**Closed by 0xSage** 2024-09-05 11:20 UTC
Labels: type: feature request
