### ISSUE TITLE
Reading local documents or networking

### ISSUE THREAD

**Issue by msjsc001** [janhq/jan#2137] opened 2024-02-23 10:21 UTC
jan When will the AI be able to read local documents while networking for chat? Very much looking forward to it

**Comment by kalle07** [comment] 2024-02-23 14:55
i tested all GPT4all and private_GPT and it doesnt work very well.
the best i have found is PDFgear! its offline and 300MB small

**Comment by msjsc001** [comment] 2024-02-23 15:20
I have used POE (poe.com) GPT4 robot, you can upload a lot of PDF and other documents to it, my largest robot has 800MB of document information, using it is like a real clone of a real expert, the effect is very amazing! But with GPT4 privacy is not guaranteed, there are some very personal and very professional questions is not good to use it to chat, will be the service provider to collect data.

I used JAN's Openchat-3.5 7B Q4 chat, I think Openchat-3.5 7B Q4 looks and GPT4 difference is not particularly big, if JAN can support on read documents, I believe it will also be very good results, offline AI has to protect the more assured. And offline AI is still iterating the future will be more powerful.

In addition you can go to this URL to see a variety of AI ratings, less than 70 points really worse, but greater than 70 offline with the effect is acceptable range, llm.extractum.io .

@kalle07

**Comment by 0xSage** [comment] 2024-06-11 01:52
dupe of https://github.com/janhq/cortex/issues/680

**Closed by 0xSage** 2024-06-11 01:52 UTC
Labels: type: feature request
