### ISSUE TITLE
bug: Downloads don't auto resume

### ISSUE THREAD

**Issue by hargup** [janhq/jan#1484] opened 2024-01-09 19:38 UTC
**Describe the bug**
Downloads don't auto resume from the previous stage if the internet connection is interrupted or the app is closed and reopended. This is important because the downloads can be pretty large.

**Expected behavior**
When the app is reopened or the interent connection resumes, restart the download from the position it was previously on.

**Environment details**
- Operating System: MacOS Sonoma 14.0
- Jan Version: 0.4.3
- Processor: Apple M1
- RAM: 16GB

**Comment by 0xSage** [comment] 2024-01-10 02:23
THank you for finding this! cc @louis-jan to triage for a future sprint

**Comment by 0xSage** [comment] 2024-01-14 14:50
dupe of #1422

**Closed by 0xSage** 2024-01-14 14:50 UTC
Labels: status: duplicate, type: bug
