### ISSUE TITLE
epic: Jan Hub recommends easiest and suitable Models, prevents OOM errors

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1179] opened 2023-12-24 03:51 UTC
## Objective

- WIP Spec

## Braindump

- Most people have only heard of Llama2, Mistral (i.e. the "brand names")
- Should we have a "Getting Started" section, that recommends very small models that they can download and use quickly?
- Should we have a "Foundational Models" section, that recommends by famous models (i.e. Llama2, Mistral)

## Tasklist

- [ ] #1008
-

**Comment by dan-jan** [comment] 2023-12-24 03:51
Suggestion from `jawenforcement` from Discord

![Image](https://github.com/janhq/jan/assets/101145494/b120e0f3-5ea5-4f36-acde-b987e0b55d2d)

**Comment by 0xSage** [comment] 2023-12-31 09:09
Closing as dupe of #850

**Closed by 0xSage** 2023-12-31 09:09 UTC
Labels: type: epic, status: needs designs, roadmap: Jan Runs Models, roadmap: Jan Hub, status: needs specs
