### ISSUE TITLE
bug: Model Hub is not fully responsive

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3181] opened 2024-07-21 21:20 UTC
### #

- [ ] I have searched the existing issues

### Current behavior

The model page where users select their desired quantization is not fully responsive. On an M1 Macbook Air, users need to use the ⌘- shortcut multiple times to see the download buttons.

### Minimum reproduction step

- HuggingFace.co
- "Use this model"
- Select Jan

### Expected behavior

The model page should be fully responsive, ensuring that all elements, including the download buttons, are visible without requiring any zoom adjustments, regardless of the device or screen size.

### Screenshots / Logs

![GSvGTzEbwAAiKFV](https://github.com/user-attachments/assets/7be99007-1808-4c74-bf9d-3ecfe3d1b806)

### Jan version

0.5.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Van-QA** [comment] 2024-08-23 09:20
![image](https://github.com/user-attachments/assets/2b984729-a770-4cc7-8dd0-581c623db727)
Reproducible ‌in Jan 0.5.2-605
Solution: ‌in‌troduce verti‌cal UI of the Hub model import

**Comment by Van-QA** [comment] 2024-08-28 08:50
![image](https://github.com/user-attachments/assets/a45c33db-d45a-4250-8193-6d69844819ff)
testing that model from earlier, and when in vertical import, the list of GGUF is not scrollable ❌

**Comment by Van-QA** [comment] 2024-08-29 04:05
![image](https://github.com/user-attachments/assets/b3984d83-e45a-4b3d-8d56-914aa4a9a46b)
The issue is resolved in Jan v0.5.2-619

**Comment by Van-QA** [comment] 2024-08-30 02:49
Jan 0.5.3 is released to stable version of Jan app: https://github.com/janhq/jan/releases/tag/v0.5.3, feel free to get back to us if any concern

**Closed by Van-QA** 2024-08-30 02:49 UTC
Labels: P1: important, type: bug
