### ISSUE TITLE
bug: Jan does not support cyrillic (maybe any non-latin symbols) in the path to models.

### ISSUE THREAD

**Issue by Glashkoff** [janhq/jan#1713] opened 2024-01-22 23:28 UTC
**Describe the bug**
Nitro fails to load the model in Windows if there is cyrillic in the path to the folder with models. This can happen when the user's name is specified in a national language.

**Steps to reproduce**
1. Create Windows user profile named, for example, 'Абв'
2. Install, run Jan and download any model.
3. Trying то chat with model.
4. You can see empty answer.
5. Jan make error in log like [NITRO]::Error: error loading model: failed to open C:\Users\Абв\jan\models\tinyllama-1.1b\tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf: No such file or directory

**Expected behavior**
Jan will allow working with local AI in chat mode.

**Environment details**
- Operating System: Windows 11 Pro x64 23H2 (build 22631.3007)
- Jan Version: 0.4.4
- Processor: AMD Ryzen 5 5600
- RAM: 32GB
- Any additional relevant hardware specifics: RTX 3060

**Logs**
/jan/logs/app.log:

`2024-01-22T23:22:36.794Z [NITRO]::CPU informations - 12
2024-01-22T23:22:36.795Z [NITRO]::Debug: Request to kill Nitro
2024-01-22T23:22:39.916Z [NITRO]::Debug: Nitro process is terminated
2024-01-22T23:22:40.432Z [NITRO]::Debug: Spawning Nitro subprocess...
2024-01-22T23:22:41.086Z [NITRO]::Debug: [93m [94m [93m [94m [93m [94m [93m_[94m_[93m_[94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m_[94m_[93m_[94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m_[94m_[93m_[94m [93m [94m [93m [94m [0m
[93m [94m [93m [94m [93m [94m/[93m_[94m_[93m/[94m [93m [94m [93m [94m [93m [94m [93m [94m_[93m_[94m_[93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m_[93m_[94m_[93m [94m [93m [94m [93m [94m [93m [94m [93m/[94m [93m [94m/[93m\[94m [93m [94m [93m [94m [93m [94m [93m [94m [93m/[94m [93m [94m/[93m\[94m [93m [94m [93m [0m
[93m [94m [93m [94m [93m [94m\[93m [94m [93m\[94m:[93m\[94m [93m [94m [93m [94m [93m [94m/[93m [94m [93m/[94m\[93m [94m [93m [94m [93m [94m [93m [94m [93m [94m/[93m [94m [93m/[94m\[93m [94m [93m [94m [93m [94m [93m/[94m [93m [94m/[93m:[94m:[93m\[94m [93m [94m [93m [94m [93m [94m [93m/[94m [93m [94m/[93m:[94m:[93m\[94m [93m [94m [0m
[93m [94m [93m [94m [93m [94m [93m\[94m [93m [94m\[93m:[94m\[93m [94m [93m [94m [93m/[94m [93m [94m/[93m:[94m/[93m [94m [93m [94m [93m [94m [93m [94m [93m/[94m [93m [94m/[93m:[94m/[93m [94m [93m [94m [93m [94m/[93m [94m [93m/[94m:[93m/[94m\[93m:[94m\[93m [94m [93m [94m [93m [94m/[93m [94m [93m/[94m:[93m/[94m\[93m:[94m\[93m [94m [0m
[93m [94m [93m_[94m_[93m_[94m_[93m_[94m\[93m_[94m_[93m\[94m:[93m\[94m [93m [94m/[93m_[94m_[93m/[94m:[93m:[94m\[93m [94m [93m [94m [93m [94m [93m [94m/[93m [94m [93m/[94m:[93m/[94m [93m [94m [93m [94m [93m/[94m [93m [94m/[93m:[94m/[93m [94m [93m\[94m:[93m\[94m [93m [94m [93m/[94m [93m [94m/[93m:[94m/[93m [94m [93m\[94m:[93m\[94m [0m
[93m [94m/[93m_[94m_[93m/[94m:[93m:[94m:[93m:[94m:[93m:[94m:[93m:[94m\[93m [94m\[93m_[94m_[93m\[94m/[93m\[94m:[93m\[94m_[93m_[94m [93m [94m [93m/[94m [93m [94m/[93m:[94m:[93m\[94m [93m [94m [93m [94m/[93m_[94m_[93m/[94m:[93m/[94m [93m/[94m:[93m/[94m_[93m_[94m_[93m [94m/[93m_[94m_[93m/[94m:[93m/[94m [93m\[94m_[93m_[94m\[93m:[94m\[0m
[93m [94m\[93m [94m [93m\[94m:[93m\[94m~[93m~[94m\[93m~[94m~[93m\[94m/[93m [94m [93m [94m [93m\[94m [93m [94m\[93m:[94m\[93m/[94m\[93m [94m/[93m_[94m_[93m/[94m:[93m/[94m\[93m:[94m\[93m [94m [93m [94m\[93m [94m [93m\[94m:[93m\[94m/[93m:[94m:[93m:[94m:[93m:[94m/[93m [94m\[93m [94m [93m\[94m:[93m\[94m [93m/[94m [93m [94m/[93m:[94m/[0m
[93m [94m [93m\[94m [93m [94m\[93m:[94m\[93m [94m [93m~[94m~[93m~[94m [93m [94m [93m [94m [93m [94m\[93m_[94m_[93m\[94m:[93m:[94m/[93m [94m\[93m_[94m_[93m\[94m/[93m [94m [93m\[94m:[93m\[94m [93m [94m [93m\[94m [93m [94m\[93m:[94m:[93m/[94m~[93m~[94m~[93m~[94m [93m [94m [93m\[94m [93m [94m\[93m:[94m\[93m [94m [93m/[94m:[93m/[94m [0m
[93m [94m [93m [94m\[93m [94m [93m\[94m:[93m\[94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m/[93m_[94m_[93m/[94m:[93m/[94m [93m [94m [93m [94m [93m [94m [93m\[94m [93m [94m\[93m:[94m\[93m [94m [93m [94m\[93m [94m [93m\[94m:[93m\[94m [93m [94m [93m [94m [93m [94m [93m [94m\[93m [94m [93m\[94m:[93m\[94m/[93m:[94m/[93m [94m [0m
[93m [94m [93m [94m [93m\[94m [93m [94m\[93m:[94m\[93m [94m [93m [94m [93m [94m [93m [94m [93m [94m\[93m_[94m_[93m\[94m/[93m [94m [93m [94m [93m [94m [93m [94m [93m [94m\[93m_[94m_[93m\[94m/[93m [94m [93m [94m [93m\[94m [93m [94m\[93m:[94m\[93m [94m [93m [94m [93m [94m [93m [94m [93m\[94m [93m [94m\[93m:[94m:[93m/[94m [93m [94m [0m
[93m [94m [93m [94m [93m [94m\[93m_[94m_[93m\[94m/[93m [94m [93m [94m [93m [
2024-01-22T23:22:41.297Z [NITRO]::Debug: Loading model with params {"llama_model_path":"C:\\Users\\Абв\\jan\\models\\tinyllama-1.1b\\tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf","ctx_len":2048,"prompt_template":"<|system|>\n{system_message}<|user|>\n{prompt}<|assistant|>","system_prompt":"<|system|>\n","user_prompt":"<|user|>\n","ai_prompt":"<|assistant|>","cpu_threads":12}
2024-01-22T23:22:41.333Z [NITRO]::Error: ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: yes

2024-01-22T23:22:41.445Z [NITRO]::Debug: 94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m\[93m_[94m_[93m\[94m/[93m [94m [93m [94m [93m [94m [93m [94m [93m [94m\[93m_[94m_[93m\[94m/[93m [94m [93m [94m [0m
[0m20240122 23:22:41.085000 UTC 32044 INFO  Nitro version:  - main.cc:44
20240122 23:22:41.086000 UTC 32044 INFO  Server started, listening at: 127.0.0.1:3928 - main.cc:48
20240122 23:22:41.086000 UTC 32044 INFO  Please load your model - main.cc:49
20240122 23:22:41.086000 UTC 32044 INFO  Number of thread is:12 - main.cc:52
20240122 23:22:41.174000 UTC 32044 INFO  Not found models folder, start server as usual - llamaCPP.h:2510
20240122 23:22:41.299000 UTC 33752 INFO  Setting up GGML CUBLAS PARAMS - llamaCPP.cc:462
{"timestamp":1705965761,"level":"INFO","function":"loadModelImpl","line":478,"message":"system info","n_threads":12,"total_threads":12,"system_info":"AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | "}

2024-01-22T23:22:41.451Z [NITRO]::Error: error loading model: failed to open C:\Users\Абв\jan\models\tinyllama-1.1b\tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf: No such file or directory
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'C:\Users\Абв\jan\models\tinyllama-1.1b\tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf'

2024-01-22T23:22:41.451Z [NITRO]::Debug: {"timestamp":1705965761,"level":"ERROR","function":"load_model","line":557,"message":"unable to load model","model":"C:\\Users\\Абв\\jan\\models\\tinyllama-1.1b\\tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"}
20240122 23:22:41.445000 UTC 33752 ERROR Error loading the model - llamaCPP.cc:482

2024-01-22T23:22:41.486Z [NITRO]::Debug: 20240122 23:22:41.486000 UTC 29104 INFO  Resolved request for task_id:0 - llamaCPP.cc:289
20240122 23:22:41.486000 UTC 29104 ERROR Sending more than 1 response for request. Ignoring later response - HttpServer.cc:355

2024-01-22T23:22:45.859Z [NITRO]::Debug: Request to kill Nitro
`

**Comment by Van-QA** [comment] 2024-01-26 16:21
@Glashkoff Please try this workaround approach with our experimental feature while we are resolving the issue:
1. Install the nightly build of Jan (Jan v0.4.4-193 or higher)
2. Move the Jan data folder to another location with no special charactor in the file path
<img width="1187" alt="image" src="https://github.com/janhq/jan/assets/64197333/b683dd35-314c-4db7-9ac9-f791b8b05e27">
3. Restart the app, install model and see if the issue resolved

**Comment by Glashkoff** [comment] 2024-01-26 17:03
@Van-QA thanks to the new option, it is now possible to change the dir to one that will contain only Latin symbols, and yes, then the model after move can be launched. However, I categorically disagree that this option is a solution to the problem of non-latin symbol support, for which I opened an issue.
It's logical that the program should support non-latin symbols in the path. In Windows, Cyrillic symbols are supported in file paths. Therefore, a program for this OS should also support these symbols. For example, if Notepad.exe can't open documents in a dir with Cyrillic names - it would be absurd to consider the solution as moving the document to the "correct" dir.

**Comment by louis-jan** [comment] 2024-02-18 07:32
I tried with a path containing special characters but couldn't reproduce it. (On Windows) 

![Screenshot 2024-02-18 142627](https://github.com/janhq/jan/assets/133622055/5bdaa520-6298-42e4-bcea-cacb8a5bf872)

Please help us try again with the latest Nightly Build and ensure that the path is accessible

**Comment by louis-jan** [comment] 2024-02-19 01:48
I tested with llama.cpp and encountered the same problem. It appears to be an issue with the engine, not the application. I will continue investigating further.

**Comment by 0xSage** [comment] 2024-09-05 05:45
Closing, if issue occurs again, should be filed upstream in respective engines, e.g. llamacpp

**Closed by 0xSage** 2024-09-05 05:45 UTC
Labels: type: feature request
