### ISSUE TITLE
bug: Model generates response non-stop (default prompt template is wrong?)

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3584] opened 2024-09-06 09:06 UTC
### #

- [X] I have searched the existing issues

### Current behavior

https://discord.com/channels/1107178041848909847/1281512188762128467/1281537450111406080
https://discord.com/channels/1107178041848909847/1239846009258119178/1281127913525088318
https://discord.com/channels/1107178041848909847/1107178593945129060/1281169582811250719

1. Models downloaded from the Jan Hub (including Llama 3) have incorrect default settings:
   - Fixed context length of 2048
   - Incorrect prompt template
   - Incorrect stop word
2. The Llama 3 model is repeating responses, producing duplicate or very similar output multiple times.
3. When importing GGUF models directly (not through the hub), settings appear correct.

### Minimum reproduction step

1. Download a GGUF model (e.g., Llama 3) from the Jan Hub
2. Observe incorrect default settings
3. Start a new conversation thread
4. Send a prompt to the model
5. Observe the repeated responses and incorrect formatting
6. Try importing the same GGUF model directly and compare settings

### Expected behavior

1. Models downloaded from the Jan Hub should have correct default settings.
2. The Llama 3 model (and other models) should provide a single, coherent response without repetition.
3. The correct prompt template should be used for proper interaction.
4. Directly imported models and hub-downloaded models should have consistent, correct settings.

### Screenshots / Logs

https://github.com/user-attachments/assets/7e7860eb-48b2-46dd-a473-c10fb85b0329

![Screenshot 2024-09-06 at 3 54 08 PM](https://github.com/user-attachments/assets/716f1186-4182-4259-b837-00a340713f20)

![Screenshot 2024-09-06 at 3 58 24 PM](https://github.com/user-attachments/assets/fa2f2174-b292-4271-beae-70c472cce779)

### Jan version

v0.5.3-623

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Environment details

Operating System: MacOS Sonoma 14.2
Processor: Apple M2
RAM: 16GB

**Comment by louis-jan** [comment] 2024-09-09 02:13
## Findings:

Ashley had already removed some of the models, and the old threads lost their model references. When she selects the thread, it automatically selects another available model. Which has a legacy of bad UX.

There is another issue created to address that (searching for it...)

**Comment by 0xSage** [comment] 2024-09-09 12:34
@louis-jan @imtuyethan I dont understand the issue, can you guys explain a bit more clearly?

is this an edge case where: 
1. Old thread
2. Model used for that thread is deleted (along with model.json)
3. User sends more messages in old thread
4. Thread autoselects some other model
5. New model has corrupted settings? How?

**Comment by tikikun** [comment] 2024-09-16 01:17
Should be able to extract chat template from gguf, not good ux

**Comment by louis-jan** [comment] 2024-09-16 01:58
> @louis-jan @imtuyethan I dont understand the issue, can you guys explain a bit more clearly?
> 
> is this an edge case where:
> 
> 1. Old thread
> 2. Model used for that thread is deleted (along with model.json)
> 3. User sends more messages in old thread
> 4. Thread autoselects some other model
> 5. New model has corrupted settings? How?

Hi @0xSage @tikikun. This is an outdated issue, it should link to the updated one. This is the case where the model is deleted and the app selects another available model to continue the conversation. However, that is an old behavior that we will update soon.

@imtuyethan please help link the new issue.

**Comment by imtuyethan** [comment] 2024-09-18 04:54
For this one: https://discord.com/channels/1107178041848909847/1281512188762128467/1281537450111406080, it's because I deleted model A, threads default to model B & the settings are not updated, so threads use model B but settings from model A, causing the weird response (wrong prompt template, etc.,...). This should be fixed via https://github.com/janhq/jan/issues/3385.

**Comment by 0xSage** [comment] 2024-10-15 07:23
dupe of #3385

**Closed by 0xSage** 2024-10-15 07:23 UTC
Labels: type: bug, category: threads & chat
