### ISSUE TITLE
bug: Show time instead of day for Today's Chats

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#326] opened 2023-10-12 02:43 UTC
**Describe the bug**
- For Chats that were touched today, should show Time instead of Date
- Similar to Whatsapp, Telegram etc

<img width="769" alt="image" src="https://github.com/janhq/jan/assets/101145494/58e7cdfb-f758-4d75-9508-b5790318e65b">

**Comment by 0xSage** [comment] 2023-10-12 05:06
Dupe of #250

**Closed by 0xSage** 2023-10-12 05:06 UTC
Labels: type: bug
