### ISSUE TITLE
feat: Widescreen mode

### ISSUE THREAD

**Issue by Ryxx** [janhq/jan#3604] opened 2024-09-09 05:25 UTC
### #

- [X] I have searched the existing issues

### Background

It would be nice to have the option to switch to a widescreen mode.
I find the "answers dialog box/column" to be too narrow. Especially when looking at code, because the line breaks make it more difficult to read. And there is a lot of wasted space on the right and left…

### Feature request

Something like this extension for ChatGPT on Chrome here:
https://chromewebstore.google.com/detail/mode-plein-%C3%A9cran-de-chatg/jgnjpnmofkalfliddjelaciggjgnphgm

Thanks.

**Comment by 0xSage** [comment] 2024-09-09 12:44
Dupe of: #3509 
Linked for reference

**Closed by 0xSage** 2024-09-09 12:44 UTC
Labels: type: feature request
