### ISSUE TITLE
bug: "No new message" in Chat List

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#325] opened 2023-10-12 02:42 UTC
**Describe the bug**
- Left Pane's Chats show "No new message"
- Should show the last message

**Comment by 0xSage** [comment] 2023-10-12 05:07
@dan-jan can you elaborate? screenshot please? expected behavior? I dont understand the bug.

**Comment by 0xSage** [comment] 2023-10-13 09:19
closing as it is a dupe of #250

**Closed by 0xSage** 2023-10-13 09:19 UTC
Labels: status: needs info, type: bug
