### ISSUE TITLE
bug: no key configured, cannot switch model within threads

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#962] opened 2023-12-13 04:33 UTC
**Describe the bug**
When i downloaded the nightly build version on 12 Dec
- The default model is OpenAI GPT 3.5 turbo & I cannot use this model because I don't have API Key, also it's not clear for users that they need to input one.
- I cannot switch model within threads.

https://github.com/janhq/jan/assets/89722390/86e47f33-1d48-4c7a-84d2-e90c88f2e6f6

https://github.com/janhq/jan/assets/89722390/3f19e3f8-b86d-411c-aa38-260465cd2fc7

**To Reproduce**
1. Download nightly build version on 12 Dec (https://discord.com/channels/1107178041848909847/1148534730359308298/1184098402871558184)
2. Open Jan -> open threads
3. See error

**Expected behavior**
- Users should be able to switch models within threads. See design flow here: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=150-5789&mode=design&t=HYyH6d0rgBz4l7Se-4
- For remote model configuration, we will have a separate UI update on that from @imtuyethan's side along with ticket https://github.com/janhq/jan/issues/850

**Desktop (please complete the following information):**
- Mac Air 16GB Ventura
- Jan v0.4.0-37

**Comment by louis-jan** [comment] 2023-12-13 04:36
@namchuai please help point @imtuyethan to the issue where we aligned that user should not able to change the model after the thread is created.

**Comment by 0xSage** [comment] 2023-12-18 04:21
Closing as a sort of dupe of #1043

**Closed by 0xSage** 2023-12-18 04:21 UTC
Labels: type: bug
