### ISSUE TITLE
docs: update Guide Uploading Images

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1131] opened 2023-12-21 01:30 UTC
**Pages**
Uploading Images: https://jan.ai/guides/chatting/upload-images/

**Success Criteria**
Content that should be covered
- [ ] How to uploading images.
- [ ] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan. 
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD

**Comment by 0xSage** [comment] 2023-12-31 08:52
Dupe of #1130

**Closed by 0xSage** 2023-12-31 08:52 UTC
Labels: status: duplicate, type: documentation, roadmap: Jan Docs
