### ISSUE TITLE
bug: Characters with accent are not displayed into the history

### ISSUE THREAD

**Issue by thonore75** [janhq/jan#3800] opened 2024-10-14 17:42 UTC
### Jan version

0.5.6

### Describe the Bug

The history list of the left side doesn't display the characters with accent.
On the provided screenshot, in the red part, it must be "Résumé de document..."

### Screenshots / Logs

![ScreenHunter 232 (01)](https://github.com/user-attachments/assets/b5518dd7-0e3a-4d9e-a2a9-cc3ac5955450)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by imtuyethan** [comment] 2024-10-17 12:33
> Operating System: MacOS Sonoma 14.2
Processor: Apple M2
RAM: 16GB
----

Cannot reproduce on my end, but might assign @urmauur to take a look:

![Image](https://github.com/user-attachments/assets/481da958-3ee7-4e06-9ac6-8dcc85369aa4)

**Comment by imtuyethan** [comment] 2024-10-18 06:56
@thonore75 Let me know if you can reproduce this bug on your end, a recording would help a lot, thanks!

**Comment by thonore75** [comment] 2024-10-18 11:26
> @thonore75 Let me know if you can reproduce this bug on your end, a recording would help a lot, thanks!


https://github.com/user-attachments/assets/61205e68-3025-464b-aaf7-716f95cea9d8

I just saw now Jan was kept my last context length but the scroll look like it was by default (4096), so which value was used ?  4096 or 61696 ?   It's why I created a feature request asking to have the model status on the "Model" tab

**Comment by imtuyethan** [comment] 2024-11-04 10:44
> > @thonore75 Let me know if you can reproduce this bug on your end, a recording would help a lot, thanks!
> 
>  ScreenHunter.54.mp4 
> I just saw now Jan was kept my last context length but the scroll look like it was by default (4096), so which value was used ? 4096 or 61696 ? It's why I created a feature request asking to have the model status on the "Model" tab

<img width="293" alt="Screenshot 2024-11-04 at 5 42 01 PM" src="https://github.com/user-attachments/assets/28faf770-595d-4bed-9744-41e698f11515">

@thonore75 I can't see or access your video.

Based on what you describe, it is a known issue:
1. When I deleted model A, threads defaulted to model B & the settings were not updated, so threads used model B but settings from model A, causing the weird responses (wrong prompt template, etc.,...). This should be fixed via https://github.com/janhq/jan/issues/3385.

2. https://github.com/janhq/jan/issues/3796

**Closed** 2024-11-04 10:44 UTC
Labels: can't reproduce, type: bug, category: threads & chat

**Comment by thonore75** [comment] 2024-11-04 11:28
Hi @imtuyethan ,

https://github.com/user-attachments/assets/d6bd88cd-f75b-47c4-a12d-b7b64790dd21

The issue is occurring with the model "dolphin-2.9.4-llama3.1-8b-Q4_0" but with  the model "Code-Mistral-7B.Q6_K" the resume in the history is in English, anyway my request was in French.
