### ISSUE TITLE
bug: Fix Download location of Nitro TensorRT on Windows

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3491] opened 2024-08-28 16:19 UTC
**Describe the bug**
The installation is not working, there is a toast msg, but users are blocked from getting to the installed status on Jan UI

**Screenshots**
![image](https://github.com/user-attachments/assets/f84342ff-7186-4b40-82e6-f76bb21e55db)

![image](https://github.com/user-attachments/assets/41d92b71-53ad-426e-95d3-05ea5f1344d9)

![image](https://github.com/user-attachments/assets/7104a7f9-b91d-4348-baf0-db22f09ba14e)

Additionally, there is an issue with system monitor in linux, that was resolved via 0.5.3
![image](https://github.com/user-attachments/assets/68e0db89-58e2-4090-9ce8-3163678f911e)

**Comment by louis-jan** [comment] 2024-08-30 03:02
System monitor issue is addressed. #3492

**Comment by imtuyethan** [comment] 2024-09-18 13:16
What installation is this? How can I reproduce?

**Comment by louis-jan** [comment] 2024-09-18 13:18
@imtuyethan TensorrtLLM requires the CUDA Toolkit to be installed, but some users may not have it set up.

Try to uninstall Cuda Toolkit, try to load a model -> Failed -> there will be a guidance message to lead you to the installation page.

**Comment by louis-jan** [comment] 2024-09-25 05:28
Root cause: 

The Tensorrt-llm on Jan is broken, as the engine repository name was changed from nitro-tensorrt-llm to cortex.tensorrt-llm.

Jan Tensort-LLM extension is downloading artifact from the repository releases. Now it's pointing to an incorrect repository.

**Comment by louis-jan** [comment] 2024-09-25 05:31
The Linux release artifact has also been removed from the engine repository. It's likely will be a part of #3690.

**Comment by dan-homebrew** [comment] 2024-09-27 02:09
@louis-jan Is there a quick fix for this that will allow us to keep legacy TensorRT-LLM extension working? 

- Cortex team will be working on TensorRT-LLM in Sprint 23 or 24 (i.e. early November)
- I would just try to keep things working, but if not possible we can also just let it fail for now

**Comment by louis-jan** [comment] 2024-09-27 02:34
Hi @dan-homebrew We can do a quick fix for Windows; it's simply a matter of replacing the URL.

But I'm not sure how Linux is enabled, since we haven't supported it in the extension yet. I'll look into it.

**Comment by dan-homebrew** [comment] 2024-09-27 05:35
@louis-jan Linux is out of scope - let's just do a quick fix for Windows, and ship it as part of 0.5.5

**Comment by luiyen** [comment] 2024-09-27 12:33
Copy!

**Comment by louis-jan** [comment] 2024-09-27 12:34
> @louis-jan Linux is out of scope - let's just do a quick fix for Windows, and ship it as part of 0.5.5

Roger that!

**Closed** 2024-09-30 04:58 UTC
Labels: type: bug, os: linux
