### ISSUE TITLE
epic: format generated code in code format (not plain text)

### ISSUE THREAD

**Issue by xx88xx** [janhq/jan#2913] opened 2024-05-16 06:47 UTC
## Motivation
Seems all the other LLMs do this now, so would be very useful comfort to have in Jan!

**Comment by Van-QA** [comment] 2024-05-16 08:41
hi @xx88xx, sorry, is this what you mean? 
![image](https://github.com/janhq/jan/assets/64197333/e1629134-99b3-49be-a429-1b32553aff9a)
The copy button will help copy code in the same format that is being displayed 🙏

**Comment by mr-september** [comment] 2024-05-20 06:44
I also sometimes run into this issue. Does anyone know if different models maybe use different syntax for things like code blocks? Like how we have multiple different prompt templates/tokens?

**Comment by xx88xx** [comment] 2024-05-20 13:19
Hi @Van-QA !
Thanks for the response. Since posting this, noticed it works in the more popular models. I agree with @mr-september sometimes it works as in the picture you attached, but often especially on some of the more bespoke models it shows up unformatted. @mr-september might be onto something with the different syntax.

**Comment by Van-QA** [comment] 2024-05-22 02:46
thank you, can you let us know more details of the failed model / step to reproduce? @xx88xx

**Comment by mr-september** [comment] 2024-06-05 05:47
With some further testing/hindsight, I think I only experienced this when using Llama3/fine-tunes released in the first week or so, where there were issues with the tokens or something, e.g.

1. https://github.com/ggerganov/llama.cpp/issues/6770
2. https://www.reddit.com/r/LocalLLaMA/comments/1cltac3/part3_cause_to_issue_found_possible_bug_llama3/

So it's likely some kind of syntax/formatting-specific thing, as previously suspected. No idea if this was also the case for @xx88xx?

**Comment by Realmbird** [comment] 2024-06-08 02:05
Can I work on this issue

**Comment by imtuyethan** [comment] 2024-07-02 18:31
> Can I work on this issue

YES PLEASE :">

**Comment by imtuyethan** [comment] 2024-07-02 18:32
Assigned @Van-QA to follow up when needed.

**Comment by imtuyethan** [comment] 2024-08-28 11:02
Hey @Realmbird how is it going so far

**Comment by 0xSage** [comment] 2024-09-05 07:19
Works for me on v0.5.3+
closing 
<img width="610" alt="image" src="https://github.com/user-attachments/assets/b22e36c4-6c01-4c16-9a6d-4109d8077176">

**Closed by 0xSage** 2024-09-05 07:19 UTC
Labels: type: feature request
