### ISSUE TITLE
feat: Add specific model selection for OpenRouter provider

### ISSUE THREAD

**Issue by ghz** [janhq/jan#3582] opened 2024-08-02 18:43 UTC
# Add specific model selection for OpenRouter provider

**Problem**
The current implementation of the OpenRouter provider in this AI project does not allow for precise model selection. Users are unable to choose specific models offered by OpenRouter, limiting the flexibility and control over the AI interactions.

**Success Criteria**
- Implement a feature that allows users to select specific AI models available through the OpenRouter provider.
- The selection process should be user-friendly and integrate seamlessly with the existing interface.
- Users should be able to view a list of available models and select their preferred one for each interaction or set a default.
- The selected model should be correctly passed to the OpenRouter API in requests.

**Additional context**
This feature would greatly enhance the project's versatility, allowing users to tailor their AI interactions to specific needs or preferences. It would also future-proof the integration with OpenRouter, as new models could be easily added to the selection list as they become available.

Some considerations for implementation:
- Fetch the list of available models from OpenRouter's API, if possible, to ensure the selection is always up-to-date.
- Consider adding a brief description or key characteristics for each model to help users make informed choices.
- Ensure proper error handling if a selected model becomes unavailable or if there are any issues with the OpenRouter API.

**Comment by 0xSage** [comment] 2024-10-17 05:57
Dupe of #3452 
ETA ~2 weeks

**Closed by 0xSage** 2024-10-17 05:57 UTC
Labels: type: feature request, category: remote providers
