### ISSUE TITLE
epic: Jan has Function Calling

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1026] opened 2023-12-15 05:20 UTC
## Resources

- https://www.reddit.com/r/LocalLLaMA/comments/18fr8u3/how_to_implement_function_calling_based_on_a/
- https://www.reddit.com/r/MachineLearning/comments/18hp7u3/p_implementing_function_calling_with/
- https://www.reddit.com/r/LocalLLaMA/comments/17ugn8i/guidance_for_selecting_a_functioncalling_library/
- https://www.reddit.com/r/LocalLLaMA/comments/180galp/whats_the_prompt_you_guys_use_for_function/
- https://www.reddit.com/r/LocalLLaMA/comments/18hjbku/optimising_function_calling_using_autogen_with/
- https://www.reddit.com/r/LocalLLaMA/comments/18i9hj4/how_do_i_get_local_llms_to_return_keywords/
- Guidance from Microsoft
- LMQL
- Grammar

**Comment by 0xSage** [comment] 2024-06-11 01:39
dupe of https://github.com/janhq/cortex/issues/295

**Closed by 0xSage** 2024-06-11 01:39 UTC
Labels: type: epic, roadmap: Create additional Copilot, roadmap: Jan as a Personal Copilot
