### ISSUE TITLE
feat: Docker Containers for Jan

### ISSUE THREAD

**Issue by SamiHK** [janhq/jan#1673] opened 2024-01-19 11:16 UTC
**Problem**
For running Jan Server on Cloud/Infra, is  it possible to have a Docker Distro for Jan?

**Success Criteria**
Having a docker image for Jan that can be running o Linux Based environments

**Comment by 0xSage** [comment] 2024-01-21 05:10
Dupe of #1078

**Closed by 0xSage** 2024-01-21 05:10 UTC
Labels: type: feature request, type: question
