### ISSUE TITLE
feat: Settings - Support new Cortex extension / 3 new engines with config

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3380] opened 2024-08-15 04:26 UTC
- Add Cortex to models provider, 1 new extension that support 3 engines (cortex.llamacpp, cortex.tensortRT, cortex.onnx) to extensions tab
- My models: Separate group of models for Cortex extension (x3 engines) and previous Nitro engines
- Hardware acceleration: remain the same - global settings
- ENH: Disabled engines should not be visible from Jan hub

**Comment by 0xSage** [comment] 2024-09-05 11:11
dupe of #3376

**Closed by 0xSage** 2024-09-05 11:11 UTC
Labels: type: feature request, roadmap: Jan x Cortex
