### ISSUE TITLE
bug: Linux Jan users are unable to type in non-English

### ISSUE THREAD

**Issue by Enchante503** [janhq/jan#3446] opened 2024-08-23 21:25 UTC
### #

- [x] I have searched the existing issues

### Current behavior

I can't enter any language other than English into the text box.

*Copy and paste is possible.

### Minimum reproduction step

Switch to your preferred language and type in the text box

### Expected behavior

The language you want to input is entered.

### Screenshots / Logs

![2024-08-24_06h23_57](https://github.com/user-attachments/assets/e59f7620-2be3-4cfd-a11e-709b51e453e4)

### Jan version

Jan v0.1.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Environment details

WSL2　Ubuntu 22.04.4 LTS

**Comment by ConstantSun** [comment] 2024-08-25 11:27
I'm also having issue : I can't paste any texts into the text box, I use Ubuntu Debian jan-linux-amd64-0.5.2.deb.

**Comment by 0xSage** [comment] 2024-09-03 05:45
@Enchante503 can I check
1. you can't type other languages in Jan at all?
2. Or when you type other languages, there is a grammar check (red squiggle) at the bottom?

@Van-QA can you check on Linux/Windows. I wasn't able to repro this bug on my Mac - works just fine

**Comment by 0xSage** [comment] 2024-09-05 11:25
Closing due to no response. Feel free to reopen if you can outline the exact issue 🙏

**Comment by dan-homebrew** [comment] 2024-09-08 14:19
@0xSage I am reopening this issue; this seems like a major problem for our users. Let's triage it and try to reproduce using Chinese and other languages on Ubuntu

**Comment by dan-homebrew** [comment] 2024-09-11 05:55
@imtuyethan I'm assigning this issue to you, can you verify it during the QA process:

- This seems to only affect Ubuntu users (and possibly Linux)
- We should try to reproduce

If we can reproduce and confirm, please assign to @urmauur to fix this sprint (i.e. Sprint 20), with view to release 0.5.5.

**Comment by imtuyethan** [comment] 2024-09-11 09:23
## Tested on:
- [x] Mac:
> Operating System: MacOS Sonoma 14.2
Processor: Apple M2
RAM: 16GB

> Operating System: MacOS Ventura 13.3.1
Processor: Apple Intel
RAM: 8GB

- [x] Window
>  114 (windows-dev-tensorRT-llm)
OS: Windows 11 Pro (Version 23H2, build 22631.4037)
CPU: AMD Ryzen Threadripper PRO 5955WX (16 cores)
RAM: 32 GB
GPU: NVIDIA GeForce RTX 3090
Storage: 599 GB local disk (C:)

> 108 (windows10-test-app)
OS: Windows 10 Pro (Version 22H2, build: 19045.4780)
CPU: Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz
RAM: 16.0 GB
System type: 64-bit operating system, x64-based processor
Installed on: 2/6/2024

- [x] Linux
> 107 (test-ubuntu-app-cpu-2)
OS: Ubuntu 22.04.4 LTS (64-bit)
CPU: Intel Xeon(R) Silver 4214R @ 2.40GHz (16 cores)
RAM: 256.0 GiB
GPU: llvmpipe (LLVM 15.0.7, 256 bits)
Storage: 429.5 GB

> 121 (test-ubuntu-app-cpu-1)
OS: Ubuntu 22.04.5 LTS (Jammy Jellyfish)
CPU: 2x Intel(R) Xeon(R) Silver 4214 processors
RAM: 16GiB System Memory
Storage: 268GB QEMU HARDDISK

## Result

**Comment by urmauur** [comment] 2024-09-12 06:04
@ConstantSun @Enchante503 hi i try on windows u guys need add keyboard input which language u guys prefer, after that make sure the ne language keyboard used,  

on windows u can 
1. go to setting open time & language and setup language do u guys prefer 
![Image](https://github.com/user-attachments/assets/5c4a4cf2-4ec2-4383-b3cc-0d46a62b8a34)


2. before use make sure u using correct keyboard, u can verify on bottom right menu
![Image](https://github.com/user-attachments/assets/f256a4c2-8ec1-4bb7-8d30-15d1f5b3d16a)

3. This is how looks like on Jan
![Image](https://github.com/user-attachments/assets/44e0c0e3-9d05-4e60-8704-7dae26893b3b)

cc @dan-homebrew @0xSage @imtuyethan 

NB @imtuyethan please take action on this ticket if no longer issue

**Comment by dan-homebrew** [comment] 2024-09-12 09:38
@imtuyethan I think you are still using the Mac keyboard on Ubuntu - can you try using the Ubuntu International Keyboard? 

- You will need to install multiple language keyboards on Ubuntu
- https://help.ubuntu.com/stable/ubuntu-help/prefs-language-install.html.en

I am fairly sure this is an issue, given the number of people who have reported it. I can also test it on my Ubuntu, but that will only be tomorrow.

**Comment by imtuyethan** [comment] 2024-09-12 11:29
Quick check @Enchante503 Can you use other languages on other apps? Because i tested on Ubuntu & it also doesn't work for other apps, maybe an OS issue not just Jan

**Comment by imtuyethan** [comment] 2024-09-13 03:22
@Enchante503 This is what we tested on our Ubuntu machine:
![ndd](https://github.com/user-attachments/assets/dcfe43e9-986a-4c7b-81a0-85d2b76b3371)
![aa](https://github.com/user-attachments/assets/ba91ea23-b7af-4a3b-8860-2e70d6bd8b7f)
![dc](https://github.com/user-attachments/assets/018a6fdb-b196-402b-b146-4d25f01a8962)

I'm curious about what tools you use to switch between languages, if possible can do a short recording & show your setup, that would help us a lot, thank you!

**Comment by dan-homebrew** [comment] 2024-09-13 05:53
@Enchante503 Can I check, what language are you trying to enter?

**Comment by dan-homebrew** [comment] 2024-09-13 06:01
> I'm also having issue : I copy some texts from other apps, but I can't paste those texts into Jan's text box, I use Ubuntu Debian jan-linux-amd64-0.5.2.deb.

@urmauur Can you update here with the your findings, and focus on the parameters we currently understand:

- v0.5.2 is affected
- We have validated Chinese not working on Ubuntu (which OS version?)

**Comment by 7ka-Hiira** [comment] 2024-09-22 21:47
What I've tried on my Arch + Jan 0.5.4:

- For Wayland, you need a command line flag to enable IME
`jan --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime`

  This is a common issue with Electron: https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Chromium_.2F_Electron

- If you want to type with fcitx(5) on X11, you need fcitx(5)-gtk.

- I couldn't reproduce the copy-paste issue

**Comment by 7ka-Hiira** [comment] 2024-09-25 09:06
I guess Ubuntu 22.04 uses Gnome on Wayland by default
Gnome doesn't seem to support text-input-v1 so 
`jan --enable-features=UseOzonePlatform --ozone-platform=x11`
worked for me. (force enabled Xwayland)

At least I don't think it's a jan issue on Linux.

I don't know about Windows, but I was able to type Japanese normally on Windows 11 (MS IME).

**Comment by urmauur** [comment] 2024-10-16 02:36
hey @dan-homebrew @0xSage @imtuyethan @Enchante503 

Here’s what I found regarding this issue:

1. @Enchante503 is running Jan on WSL2 - Ubuntu 22.04.4 LTS, which is a subsystem.
2. I encountered the same issue as @Enchante503 when running Jan locally inside the WSL subsystem.
3. 	There are known issues with `subsystems` not handling keyboard input properly:
  - https://github.com/microsoft/WSL/issues/9954
  - https://github.com/microsoft/wslg/issues/1184
4. I confirmed with Alex that he is running Jan locally and the latest production dist of Linux (without a subsystem), and the keyboard works fine.

Conclusion: From my perspective, this isn’t a bug with Jan or our input chat box. The issue seems to be related to running Jan within a subsystem, as mentioned in point 3.

**Comment by dan-homebrew** [comment] 2024-10-20 02:48
@Enchante503 Will do - it's tracked here: https://github.com/janhq/jan/issues/3792

> [#2585 (comment)](https://github.com/janhq/jan/issues/2585#issuecomment-2423025165)
> 
> This has been resolved. However, a WebUI using a browser is more convenient. Please consider this.

**Closed by dan-homebrew** 2024-10-20 02:48 UTC
Labels: P1: important, type: bug, category: threads & chat, os: linux
