### ISSUE TITLE
bug: LaTeX rendering issue

### ISSUE THREAD

**Issue by thethinkmachine** [janhq/jan#2865] opened 2024-05-04 02:50 UTC
**Describe the bug**
Jan has issues with properly displaying mathematical content. When inline mathematical statements (enclosed within single `$` delimiters) are used, the output duplicates the expression alongside the rendered LaTeX expression. Additionally, matrices enclosed within double `$$` delimiters are not displayed correctly, with the application using small, fixed sized curved braces instead of the appropriate larger square brackets. Furthermore, rendering larger matrices, such as an n x n Jacobian (a matrix containing partials), is sometimes a hit or a miss, sometimes it fails to display the matrix completely.

**Steps to reproduce**
1. Launch the Jan application and load a model (e.g., Llama 3 8B Q6).
2. Ask it to print an inline mathematical expression (e.g., `$E = mc^2$`), it'll get duplicated next to the latex expression in the output.
3. Ask it to print a matrix enclosed within `$$` delimiters (e.g., `$$\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$$`), it uses small, curved braces instead of larger square braces to enclose the matrix.
4. Ask it to print the following LaTeX syntax.

```
$$\frac{\partial \nabla\phi}{\partial \mathbf{x}} = \begin{bmatrix}
\frac{\partial \nabla_x \phi}{\partial x} & \frac{\partial \nabla_x \phi}{\partial y} & \frac{\partial \nabla_x \phi}{\partial z} \\
\frac{\partial \nabla_y \phi}{\partial x} & \frac{\partial \nabla_y \phi}{\partial y} & \frac{\partial \nabla_y \phi}{\partial z} \\
\frac{\partial \nabla_z \phi}{\partial x} & \frac{\partial \nabla_z \phi}{\partial y} & \frac{\partial \nabla_z \phi}{\partial z}
\end{bmatrix}$$
```
It renders the provided text as is.

**Expected behavior**
The expected behavior can be observed by copying and pasting the above LaTeX syntax into Obsidian, a note-taking application with proper LaTeX rendering capabilities. In Obsidian, the inline mathematical statements should be rendered correctly without duplication, and the matrices should be displayed using the appropriate square brackets and formatting. The larger, more complex matrices should also be rendered correctly, displaying the content in a visually appealing and mathematically accurate manner.

**Screenshots**
- Not required (The bug is reproducible).

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.12
- Processor: AMD Ryzen 5 3600
- RAM: 16GB
- GPU: NVIDIA RTX 2070 Super (8 GB DDR6 VRAM)
- System prompt: You are a helpful assistant designed to assist reasoning in mathematical tasks & subjects.

**Comment by Van-QA** [comment] 2024-05-06 04:14
The issue is reproducible :x:
![image](https://github.com/janhq/jan/assets/64197333/fe5a584f-9430-411a-aeb3-ba771f19981b)
![image](https://github.com/janhq/jan/assets/64197333/a8b03363-d0ee-4c84-8283-d7e862187a88)

**Comment by Van-QA** [comment] 2024-08-29 04:07
The issue is resolved in Jan v0.5.2-619

**Comment by Van-QA** [comment] 2024-08-30 02:51
Jan 0.5.3 is released to stable version of Jan app: https://github.com/janhq/jan/releases/tag/v0.5.3, feel free to get back to us if any concern

**Closed by Van-QA** 2024-08-30 02:51 UTC
Labels: type: bug

**Comment by thethinkmachine** [comment] 2024-08-30 11:54
Sure, thank you very much.
