### ISSUE TITLE
feat: Assistant Instruction Library

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1364] opened 2024-01-05 02:58 UTC
**Problem**
Assistant instruction is a static input with no way to save variants in Jan.

**Success Criteria**
Either a drop down or an open file to grab saved instructions

**Additional context**
None.

**Comment by 0xSage** [comment] 2024-01-05 07:42
Dupe of #901  and #755

**Closed by 0xSage** 2024-01-05 07:42 UTC
Labels: status: duplicate, type: feature request
