### ISSUE TITLE
Does not infer on Snapdragon based Windows laptop

### ISSUE THREAD

**Issue by 77poker125** [janhq/jan#2506] opened 2024-03-26 15:53 UTC
I'm using a Qualcomm Snapdragon (ARM64) based Windows laptop and I am not getting responses from models.

**Steps to reproduce**
I downloaded the Llama 2 7B Chat Q4 model and tried to ask it a question. No inference occurred.

I then downloaded the Gemma 2B Q4 model and tried to ask it a question. No inference occurred.

![Screenshot 2024-03-26 114940](https://github.com/janhq/jan/assets/121313734/f994294f-cfa4-4951-bbcb-4f7c8b4d9b0c)

**Environment details**
Windows 11 build 26068
Jan version 0.4.9
Qualcomm Snapdragon processor
64GB RAM

[app.log](https://github.com/janhq/jan/files/14761146/app.log)

**Comment by Van-QA** [comment] 2024-03-27 04:25
Related to https://github.com/janhq/jan/issues/2489. @hiro-v

**Comment by louis-jan** [comment] 2024-04-23 07:55
Pending NPM & CLI update, more architectures supported

**Comment by 0xSage** [comment] 2024-06-11 02:15
dupe of https://github.com/janhq/cortex/issues/623

**Closed by 0xSage** 2024-06-11 02:15 UTC
Labels: type: bug
