### ISSUE TITLE
bug: Unsupported Parameter Errors for model `o1-mini` & `o1-preview` 

### ISSUE THREAD

**Issue by PucaVaz** [janhq/jan#3745] opened 2024-09-30 21:09 UTC
### Jan version

v0.5.4-649

### Describe the Bug

I can't disable the stop words, so I get this error 

```
Unsupported parameter: 'stop' is not supported with this model.
Jan’s in beta. Access troubleshooting assistance now.
```

### Steps to Reproduce

Just try to use the newer model from open ai, the o1-preview 

### Screenshots / Logs

<img width="276" alt="Screenshot 2024-09-30 at 18 06 41" src="https://github.com/user-attachments/assets/b15aa10f-c7cc-4161-b46b-4659b760d557">
### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment] 2024-10-17 11:41
Duplicate with https://github.com/janhq/jan/issues/3771

Reproducible:

![Image](https://github.com/user-attachments/assets/9a8eb7e6-89a3-45c4-897f-f02c26602f58)

**Comment by imtuyethan** [comment] 2024-10-17 11:49
Should be fixed as a part of https://github.com/janhq/jan/issues/3505

**Comment by imtuyethan** [comment] 2024-10-18 07:42
Related #3771

**Comment by louis-jan** [comment] 2024-11-15 03:18
Hi @PucaVaz @imtuyethan. Could you please help try the latest version, 0.5.8, to see if the issue has been resolved?

**Comment by PucaVaz** [comment] 2024-11-15 10:27
@louis-jan for sure, just one second

**Comment by PucaVaz** [comment] 2024-11-15 10:50
Now it's work, but not by default, i need to change a few things, in order to work, by setting the temperature to 1, top P to 1 and stream to off, it's cool that now works

<img width="1341" alt="Screenshot 2024-11-15 at 07 34 06" src="https://github.com/user-attachments/assets/09e71090-f3bb-4b51-bdc8-dfd392e12551">
It's strange that if an error occurs, the message doesn't say anything about it.
<img width="703" alt="Screenshot 2024-11-15 at 07 36 22" src="https://github.com/user-attachments/assets/e3e589e7-5522-4b2d-a785-40b944e46bcd">

**Comment by louis-jan** [comment] 2024-11-15 11:02
Thanks @PucaVaz, we’ll handle the message error gracefully in the next hotfix.

**Comment by imtuyethan** [comment] 2024-11-18 10:29
I'll close this one as dup.

**Comment by imtuyethan** [comment] 2024-11-18 10:42
@louis-jan Can reproduce on my end:


https://github.com/user-attachments/assets/c4fac884-bafd-4de5-a7a1-73cb491041b1

**Comment by imtuyethan** [comment] 2024-11-20 09:03
They work now; however:
- There's no way to adjust the stream settings? I can't see the option to turn it on & off. Now, all responses default to turn off stream. 
- This is a big friction in user experience because the `Generating Response` indicator feels stuck & unnatural over a simple prompt. 

`OpenAI o1-mini`
https://github.com/user-attachments/assets/a0416705-83d4-4bd0-8ca9-d2aa9ca060eb

`OpenAI o1-preview`

https://github.com/user-attachments/assets/63da2e9e-16e1-4e3c-ba2c-2b00f9397831

cc @louis-jan

**Comment by louis-jan** [comment] 2024-11-20 09:25
@imtuyethan o1 beta models do not support stream. See https://openai.com/index/introducing-openai-o1-preview/
The API for these models currently doesn't include function calling, streaming, support for system messages, and other features

**Comment by imtuyethan** [comment] 2024-11-20 15:49
Updated: will fix

**Closed** 2024-11-21 08:12 UTC
Labels: duplicate, type: bug, category: model support, category: providers, category: model settings, move to Cortex
