### ISSUE TITLE
Implement desktop app analytics

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#727] opened 2023-11-27 03:26 UTC
Tracking plan for Jan app (cc @urmauur for early research)

- Active users
- Locations
- Version usage
- Feature Usage
- Platform usage

Eventually we want to create a page like this: https://data.syncthing.net/ 

For further support, please contact @tikikun @louis-jan

**Comment by 0xSage** [comment] 2023-11-29 02:56
Currently blocked on app refactoring. Revisit next week / week of Dec 3

**Comment by louis-jan** [comment] 2023-12-07 06:17
@namchuai could you pleas take this? The idea is: 
- We can plug analytics-extension in to define analytics module
- User can opt-out via UI
- Track important actions / features in app

**Comment by dan-jan** [comment] 2023-12-11 08:58
Duplicate of #493

**Closed by dan-jan** 2023-12-11 08:58 UTC
Labels: P1: important, good first issue, type: feature request
