### ISSUE TITLE
bug: 1 token after 5 minutes for Jan on Windows without GPU

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#544] opened 2023-11-05 05:00 UTC
**Problem**

Most of the laptops for students and even laptop cho công sử don't have good GPUs or actually, they don't have any GPUs. They will take time to respond to a request while using Jan.

We also need to think of Windows users too.

**Comment by dan-jan** [comment] 2023-11-05 13:28
Updated issue with correct tags. Feedback: 

- Please use bug template when filing bugs (the actual hardware, etc are useful for debugging)
- Issue should be more descriptive

**Comment by hahuyhoang411** [comment] 2023-11-05 18:15
Update the specs and problem description.

The problem appears while using the model "openhermes-2-mistral-7b.Q5_K_M.ggufv1.0.0". The CPU peaked at around 95-99% while the Mem was around 80% when chatting.

- OS: Windows 10
- Hardware: 
+ CPU: Intel Core i5 Tiger Lake - 1135G7
+ GPU: No
+ RAM: 8GB
- Jan version: 0.3.0 (for Windows)

**Additional feedback**
- There is no UI for waiting for the response of an assistant so the user doesn't know whether it's running or lagging.

**Comment by hahuyhoang411** [comment] 2023-11-05 18:19
**My observation after trying to reproduce the problem**
- If user downloads and uses the model directly, it works fine. However, if user closes Jan and restarts the model, the problem will appear.
-> Workaround solution, goes to `%APPDATA%` and deletes entirely model.gguf file. Reinstall it and it works perfectly.

**Comment by louis-jan** [comment] 2023-11-16 03:39
Please update your test result on this @hahuyhoang411. Is the issue addressed or still exist?

**Comment by linhtran174** [comment] 2023-11-17 00:56
I cannot reproduce this, and also synced with @hahuyhoang411. This issue is replaced with the new one, so closing this.

**Closed by linhtran174** 2023-11-17 00:56 UTC
Labels: type: bug
