### ISSUE TITLE
Opt-in Analytics / Crash reporting for Jan

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3486] opened 2024-08-28 09:29 UTC
Specs: https://www.notion.so/jan-ai/Opt-in-Analytics-Crash-reporting-for-Jan-3270063062bf4496ad9ab9e2542fd15c?pvs=4

**Comment by dan-homebrew** [comment] 2024-08-28 10:46
@imtuyethan From my perspective, we should break this up into two different epics: 

- Crash Reporting
- Opt-in Analytics

Both of these will go into the Privacy tab in Settings, but are conceptually different and should be recognized with different epics.

**Comment by dan-homebrew** [comment] 2024-08-30 07:31
Duplicate of #3119

**Closed by dan-homebrew** 2024-08-30 07:31 UTC
Labels: type: epic
