### ISSUE TITLE
feat: Affix the order of properties in Threads Right Panel

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1189] opened 2023-12-25 10:03 UTC
**Describe the bug**
Stream changes its position when i create a new thread:

https://github.com/janhq/jan/assets/89722390/3e483e36-e873-406c-a78f-424df8b0b185

**To Reproduce**
1. Create a thread with any model (let's call it A)
2. Create another thread using model A again
3. When click between 2 threads, will see the bug

**Expected behavior**
Stream position should not be changed.

**Desktop:**
- Jan v0.4.3
- Mac Air 16GB Sonoma 14.2

**Comment by 0xSage** [comment] 2023-12-26 02:52
@imtuyethan this is currently intended behavior, as the Right panel is autogenerated from files. If the fields are in different orders, they will render in different orders. 

One hack around it is to force the UI to alphabetically sort the fields. Among other options. I'll let you think thorugh the ideal behavior here.

**Comment by namchuai** [comment] 2023-12-28 02:12
@0xSage @imtuyethan this issue will be fixed in #1199

**Closed by namchuai** 2023-12-28 02:12 UTC
Labels: type: enhancement
