### ISSUE TITLE
feat: Apple Ferret and MLX

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1181] opened 2023-12-24 05:50 UTC
## Objective

- WIP spec

## Resources

- Apple Ferret
- Need to support MLX
- Support Quantization
- https://www.reddit.com/r/LocalLLaMA/comments/18oke4y/apples_mlx_framework_adds_quantization_support/

**Comment by tikikun** [comment] 2024-01-11 02:55
blocked by Python runtime

**Comment by 0xSage** [comment] 2024-06-11 01:41
dupe of https://github.com/janhq/cortex/issues/678

**Closed by 0xSage** 2024-06-11 01:41 UTC
Labels: type: feature request, engineering: Jan Inference Layer
