### ISSUE TITLE
bug: Windows: "Nitro process exited. 1" when trying to run Inference

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#928] opened 2023-12-09 12:03 UTC
**Describe the bug**
- I encounter a bug where Nitro process exits immediately when trying to load model 
- See screenshot below

**To Reproduce**
1. Run Jan and download tinyllama
2. Send a message to Jan using tinyllama

**Screenshots**
![image](https://github.com/janhq/jan/assets/101145494/538e3c63-6e07-46bc-87c0-02cb18a931d4)

**Desktop (please complete the following information):**
 - OS and Hardware (please see below)
 - 11th Gen Intel, 16gb RAM
 - Windows 10 Pro
![image](https://github.com/janhq/jan/assets/101145494/ecc0a577-9cd3-404d-b9cc-58c9a3271342)

**Additional context**

**Comment by dan-jan** [comment] 2023-12-11 08:30
@linhtran174 I'm reassigning this task to you

**Comment by linhtran174** [comment] 2023-12-12 09:45
Mistakenly linked to another merged PR, re-opening this

**Comment by linhtran174** [comment] 2023-12-12 10:18
I cannot reproduce this on my Windows PC, also tried a fresh clone and build on Hiro's laptop, download tinyllama and it works perfectly: 

![image](https://github.com/janhq/jan/assets/8022780/3dd0b8fc-963c-4060-94ec-386c2b0601a4)
Hiro's laptop spec:
![image](https://github.com/janhq/jan/assets/8022780/f5693bec-608c-4936-98f9-c67559f9d4a7)

**Comment by louis-jan** [comment] 2023-12-12 10:39
@linhtran174 please give the possible root cause we mentioned. Old tinylama models spec contains empty ai_prompt and user_prompt. @dan-jan please check if this is the case. Delete /models does help with @linhtran174 case.

**Comment by linhtran174** [comment] 2023-12-13 02:05
Ty for supplementing. As root cause is found, I will close the ticket with summry:
- Cause: legacy model spec not compatible with new spec
- Solution: Delete /models in JAN_ROOT and restart

**Closed by linhtran174** 2023-12-13 02:05 UTC
Labels: type: bug, windows
