### ISSUE TITLE
bug: Jan Windows experiences intermittent Flickering issues

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1219] opened 2023-12-26 15:25 UTC
**Describe the bug**
Bug reported by Sabin_Stargem from r/localllama
- [ ] Reproduce Bug
- [ ] Follow in [r/localllama thread](https://www.reddit.com/r/LocalLLaMA/comments/18pyul4/comment/kezkxpv/?utm_source=share&utm_medium=web2x&context=3)

![Image](https://github.com/janhq/jan/assets/101145494/50db6849-00ac-41d9-98e4-8bf8bbaabb7c)

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.3 (assumed)
- Ryzen 5950x
- 128gb RAM

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by SabinStargem** [comment] 2023-12-26 19:04
It should be noted, that my rig also has two RTX 3060 cards.

**Comment by louis-jan** [comment] 2024-03-06 03:53
I think the issue is related to https://github.com/janhq/jan/issues/1650. We can close it for now and reopen it if the issue still occurs.

**Closed** 2024-03-06 04:25 UTC
Labels: type: bug, platform: Windows
