### ISSUE TITLE
Add AI Model Rating Indicators

### ISSUE THREAD

**Issue by msjsc001** [janhq/jan#2209] opened 2024-03-02 03:22 UTC
Dear Jan.ai Development Team,

Hello! I am an enthusiastic user of the Jan.ai platform. My attention was recently drawn to the Gemma model, which was touted as the most powerful offline model by a YouTuber. However, upon further investigation within the Jan community on Discord, I found out that the Mistral model might be superior in certain aspects.

The discrepancy between the YouTuber's claims and the community insights highlighted the need for a reliable and user-friendly AI model rating system—similar to what llm.extractum.io offers. Such a system would vastly benefit users like me, who are not deeply versed in the technical nuances of AI models, by providing an intuitive way to assess a model's overall capabilities and areas of strength.

I am reaching out to suggest the integration of a model rating system within Jan.ai or, at the very least, provide a link to an existing authoritative rating platform like llm.extractum.io. It would significantly enhance the user experience by empowering us to make more informed decisions when selecting the most suitable model for our needs.

The addition of a rating system would alleviate the need to download and trial multiple models to determine the best fit, saving time for users and reducing the load on the system. I believe this feature would be a substantial value add to the Jan.ai community and align with the goals of making AI more accessible and user-oriented.

I look forward to your response and hope my suggestion will be considered for implementation. Thank you for your time and dedication to improving the Jan.ai user experience.

Best regards,
msjsc001

**Comment by 0xSage** [comment] 2024-06-11 02:06
dupe of https://github.com/janhq/cortex/issues/610
though we prob wont show this at hte ui level

**Closed by 0xSage** 2024-06-11 02:06 UTC
Labels: type: feature request
