### ISSUE TITLE
epic: Jan deployable as cloud-native

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#255] opened 2023-10-03 03:40 UTC
## Problem

- User doesn't have a local GPU machine but wants to run Jan on a rented server
- User wants a quick, fast way to experiment with Jan on a rented GPU

## Success Criteria

- User is able to deploy Jan on Runpod with minimal difficulty
- Jan is listed as a template on Runpod, AWS, Azure, etc)

## Sub Issues

- Jan's codebase should be architected to support both Desktop-native and Cloud-native build targets
- Jan's plugin architecture should work identically across Desktop-native and Cloud-native
- We should have a "simple-auth" plugin that allows cloud-native deployment to have simple username/password auth (definable in `env` variables or equivalent)
- [KIV] We should also start thinking of a strategy where the `data-plugin` can support different database types
    - Currently only supports `sqlite`
    - Cloud-native offers postgres, etc

### Similar Products

- Discord and Slack run on Web, as well as Desktop app

### Examples

- https://www.runpod.io/console/templates
- https://repost.aws/articles/ARQ0Tz9eorSL6EAus7XPMG-Q/how-to-install-textgen-webui-on-aws
- https://www.youtube.com/watch?v=_59AsSyMERQ
- https://gpus.llm-utils.org/running-llama-2-on-runpod-with-oobaboogas-text-generation-webui/
- https://medium.com/@jarimh1984/installing-oobabooga-and-oobabooga-api-to-runpod-cloud-step-by-step-tutorial-47457974dfa5

**Comment by 0xSage** [comment] 2023-11-10 07:00
Dupe of #200

**Closed by 0xSage** 2023-11-10 07:00 UTC
Labels: P1: important, type: epic
