### ISSUE TITLE
feat: Thread Settings' inference and engine parameters should reflect the values provided in model's json file

### ISSUE THREAD

**Issue by leitdeux** [janhq/jan#1463] opened 2024-01-08 22:37 UTC
**Problem**
Currently, it appears that the max values for Max Tokens and Context Length sliders is 4096, however, there are models such as Mistral Instruct 7B v0.2 that support values up to 32k. Even if one manually edits the model json file to set these values to 32k (for example), in Jan, the slider values are capped at 4096 and thus the user cannot easily lower the Context Length value to, for example, 16k. The user is limited to setting the max slider value to 4096 regardless of the actual capabilities of the given model selected for a thread.

**Success Criteria**
Upon selection of a given available model in the Thread Settings sidebar, the app should update the max slider values of Max Tokens and Context Lengths to those provided in the model's corresponding model JSON file. Therefore, a user should be able to choose between the min slider value(s) to the max slider value(s) as dictated by the selected model.

**Additional context**
In this screenshot you can a see a model that I manually imported, "Mistral Instruct 7B Q4 v0.2", which supports a Context Length greater than 4096. However, the slider does not reflect this, as its max slider value position remains at 4096.
![スクリーンショット 2024-01-09 7 28 27](https://github.com/janhq/jan/assets/16680740/721ab97c-24eb-491f-aea8-c645afe72390)

Here is my custom `model.json` for this model. 
**NB: I believe that this model actually has a context length up to 32k, however I set it to a lower value for better performance on my machine, hence why the values are 16384 in the JSON file below:**

``` json
 {
    "source_url": "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf",
    "id": "mistral-instruct-7b-q4-v0.2",
    "object": "model",
    "name": "Mistral Instruct 7B Q4 v0.2",
    "version": "1.0",
    "description": "This is a 4-bit quantized iteration of MistralAI's Mistral Instruct 7b model, specifically designed for a comprehensive understanding through training on extensive internet data.",
    "format": "gguf",
    "settings": {
      "ctx_len": 16384,
      "prompt_template": "<s>[INST]{prompt}\n[/INST]"
    },
    "parameters": {
      "max_tokens": 4096
    },
    "metadata": {
      "author": "MistralAI, The Bloke",
      "tags": ["Featured", "7B", "Foundational Model"],
      "size": 4370000000,
      "cover": "https://raw.githubusercontent.com/janhq/jan/main/models/mistral-ins-7b-q4/cover.png"
    },
    "engine": "nitro"
  }
```

**Comment by 0xSage** [comment] 2024-01-11 09:29
Dupe of #1427

**Closed by 0xSage** 2024-01-11 09:29 UTC
Labels: status: duplicate, type: feature request
