### ISSUE TITLE
bug: UI not rendering for Wizard Coder [Model Checksum]

### ISSUE THREAD

**Issue by SmokeShine** [janhq/jan#2754] opened 2024-04-18 13:03 UTC
**Describe the bug**
I have downloaded Wizard coder and it is not displaying the results correctly.  I have added the screenshot.

**Steps to reproduce**
1. Go to 'New Thread'
2. "how to print hello world in python" Click on 'Send'
3. See error

**Expected behavior**

**Screenshots**
<img width="897" alt="image" src="https://github.com/janhq/jan/assets/37322071/ebeaf05f-fe2c-4426-98d5-2a21b5a50601">

**Environment details**
- Operating System: MacOS Sonoma 14.0.0
- Jan Version:  v0.4.11
- Processor: Apple M1
- RAM: 16GB
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` 

2024-04-18T12:59:10.902Z [NITRO]::Error: ggml_metal_graph_compute: command buffer 0 failed with status 5

2024-04-18T12:59:10.905Z [NITRO]::Error: ggml_metal_graph_compute: command buffer 0 failed with status 5

2024-04-18T12:59:10.905Z [NITRO]::Error: ggml_metal_graph_compute: command buffer 0 failed with status 5

2024-04-18T12:59:10.907Z [NITRO]::Error: ggml_metal_graph_compute: command buffer 0 failed with status 5

2024-04-18T12:59:10.906Z [NITRO]::Error: ggml_metal_graph_compute: command buffer 0 failed with status 5

2024-04-18T12:59:10.889Z [NITRO]::Error: ggml_metal_graph_compute: command buffer 0 failed with status 5

2024-04-18T12:59:10.826Z [NITRO]::Error: ggml_metal_graph_compute: command buffer 0 failed with status 5

**Comment by Van-QA** [comment] 2024-04-19 04:14
The issue is not reproducible 
![image](https://github.com/janhq/jan/assets/64197333/424a8ef2-f400-4ea5-af50-8bbcfdce281e)
cc: @hahuyhoang411 to take a look, thank you

**Comment by SmokeShine** [comment] 2024-04-19 08:23
Did you try to reproduce the issue on Apple M1? I reinstalled the Jan application, added the model again. The issue is restricted to this model. I can use codeqwen-1_5 and it has no UI issue.

**Comment by louis-jan** [comment] 2024-04-22 07:26
I think there is a problem with the downloaded model. The stats are unreal; I'm using an M2 Pro with 32 GB of RAM, but the token speed is around 17 tokens/s (your case 176T/s). Could you please try a factory reset from the settings page and download the model again, ensuring the connection is not corrupted? @SmokeShine

**Comment by SmokeShine** [comment] 2024-04-22 07:43
> I think there is a problem with the downloaded model. The stats are unreal; I'm using an M2 Pro with 32 GB of RAM, but the token speed is around 17 tokens/s (your case 176T/s). Could you please try a factory reset from the settings page and download the model again, ensuring the connection is not corrupted? @SmokeShine 

Is there any checksum for validating the downloaded file?

**Comment by louis-jan** [comment] 2024-04-23 02:13
Sorry @SmokeShine, there isn't a checksum added yet to validate.

**Comment by Van-QA** [comment] 2024-05-29 09:01
Closing this for now, please fo‌llowing up in https://github.com/janhq/jan/issues/2858 for checks‌‌um validation

**Closed by Van-QA** 2024-05-29 09:01 UTC
Labels: P1: important, type: bug
