### ISSUE TITLE
bug: New threads's instruction settings persist incorrectly when switching to old threads

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3522] opened 2024-09-02 11:17 UTC
### #

- [X] I have searched the existing issues

### Current behavior

https://discord.com/channels/1107178041848909847/1279360618318663712
Alan was experiencing an issue where settings from newly created threads are incorrectly applied to old threads when navigating through conversation history.

### Minimum reproduction step

1. Open Jan and start a new thread
2. Configure settings for the new thread
3. Go back to view conversation history
4. Open an old thread
5. Observe that the settings from the new thread are applied to the old thread

### Expected behavior

When opening an old thread from the history, new threads should retain its original settings, maybe autosave for users?

### Screenshots / Logs

https://github.com/user-attachments/assets/6689077f-285f-48bc-a1ab-7e9768db920e

### Jan version

v0.5.3-620

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Environment details

-

**Comment by 0xSage** [comment] 2024-09-03 07:25
Is this a bug or a feature? I feel like it's kind of a cool feature.
Was this filed by a user?

**Comment by 0xSage** [comment] 2024-09-06 03:56
Tested on 623. 

- Instructions are sticky to the thread it was created for.
- Behaving as intended.

closing

**Closed by 0xSage** 2024-09-06 03:56 UTC
Labels: type: bug
